apps/courses/urls.py
# -*- coding:utf-8 -*-
__author__ = 'chenziang'
__date__ = '2017/5/30 13:22'

from django.conf.urls import url
from .views import CourseCommentView,CourseDetailView,CourseListView,CourseVideoView,AddCommentView,VideoPlayView

urlpatterns = [
    # 课程列表页
    url(r'^list/$',CourseListView.as_view(),name='course_list'),

    # 课程详情页
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='course_detail'),

    # 课程评论
    url(r'^comment/(?P<course_id>\d+)/$',CourseCommentView.as_view(),name='course_comment'),

    # 课程视频
    url(r'^video/(?P<course_id>\d+)/$', CourseVideoView.as_view(), name='course_video'),

    # 添加课程评论
    url(r'^add_comment/$', AddCommentView.as_view(), name='add_comment'),

    # 播放视频地址
    url(r'^video_play/(?P<video_id>\d+)/$', VideoPlayView.as_view(), name='video_play'),
]

apps/organization/urls.py
# -*- coding:utf-8 -*-
__author__ = 'chenziang'
__date__ = '2017/5/19 13:51'

from django.conf.urls import url

from .views import OrgView,OrgHomeView,OrgCourseView,OrgDescView,OrgTeacherView,AddFavView,TeacherListView,TeacherDetailView

urlpatterns = [
    # 机构列表
    url(r'^list/$',OrgView.as_view(),name='org_list'),

    # 机构主页
    url(r'^home/(?P<org_id>\d+)$', OrgHomeView.as_view(), name='org_home'),

    # 机构课程
    url(r'^course/(?P<org_id>\d+)$', OrgCourseView.as_view(), name='org_course'),

    # 机构描述
    url(r'^descs/(?P<org_id>\d+)$', OrgDescView.as_view(), name='org_desc'),

    # 机构教师
    url(r'^teacher/(?P<org_id>\d+)$', OrgTeacherView.as_view(), name='org_teacher'),

    # 授课教师
    url(r'^teacher/list/$', TeacherListView.as_view(), name='teacher_list'),

    # 教师详情
    url(r'^teacher_detail/(?P<teacher_id>\d+)$', TeacherDetailView.as_view(), name='teacher_detail'),

    # 机构收藏
    url(r'^add_fav/$', AddFavView.as_view(), name='add_fav'),
]

apps/users/urls.py
# -*- coding:utf-8 -*-
__author__ = 'chenziang'
__date__ = '2017/6/17 21:13'

from django.conf.urls import url
from .views import UserInfoView,MyCourseView,UploadImageView,UpdatePwdView,SendEmailCodeView,\
    UpdateEmailView,MyFavOrgView,MyFavCourseView,MyFavTeacherView,MyMessageView

urlpatterns = [
    # 用户个人中心
    url(r'^info_center/$',UserInfoView.as_view(),name='info_center'),

    # 我的课程
    url(r'^my_course/$', MyCourseView.as_view(), name='my_course'),

    # 我收藏的大学
    url(r'^my_fav_org/$', MyFavOrgView.as_view(), name='my_fav_org'),

    # 我收藏的教师
    url(r'^my_fav_teacher/$', MyFavTeacherView.as_view(), name='my_fav_teacher'),

    # 我收藏的课程
    url(r'^my_fav_course/$', MyFavCourseView.as_view(), name='my_fav_course'),

    # 我的消息
    url(r'^my_message/$', MyMessageView.as_view(), name='my_message'),

    # 修改头像
    url(r'^upload_image/$', UploadImageView.as_view(), name='upload_image'),

    # 修改password
    url(r'^update_pwd/$', UpdatePwdView.as_view(), name='update_pwd'),

    # 发送邮箱验证码（个人中心）
    url(r'^send_code/$', SendEmailCodeView.as_view(), name='send_code'),

    # 就修改绑定邮箱（个人中心）
    url(r'^update_email/$',UpdateEmailView.as_view(),name='update_email')
]

mxzx/urls.py
# -*- coding:utf-8 -*-
"""mxzx URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""

from django.conf.urls import url,include
import xadmin
from users.views import LoginView, RegisterView, ForgetPwdView, RedirectToResetView,\
    ResetPwdView, IndexView, LogOutView

from django.views.static import serve
from mxzx.settings import MEDIA_ROOT,STATIC_ROOT
from courses.views import SearchView

urlpatterns = [

    # 后台管理
    url(r'^admin/', xadmin.site.urls),

    # 首页
    url(r'^$',IndexView.as_view(), name='index'),

    # 登录
    url(r'^login/$',LoginView.as_view(), name='login'),

    # 注册页面
    url(r'^register/$',RegisterView.as_view(), name='register'),

    # 登出
    url(r'^logout/$',LogOutView.as_view(), name='logout'),

    # 校验码
    url(r'^captcha/', include('captcha.urls')),

    # 忘记密码
    url(r'^forget_pwd/$',ForgetPwdView.as_view(), name='forget_pwd'),

    # 打开邮箱里重置密码的链接，执行此处，跳转到密码重置页面
    url(r'^RedirectToReset/(?P<activate_code>.*)/$', RedirectToResetView.as_view(), name='RedirectToReset'),

    # 重置密码
    url(r'^resetpwd',ResetPwdView.as_view(), name='resetpwd'),

    # 搜索结果
    url(r'^search_result',SearchView.as_view(), name='search_result'),

    # 机构相关的url配置
    url(r'^org/',include('organization.urls', namespace='org')),

    # 课程相关url
    url(r'course/',include('courses.urls', namespace='course')),

    # 用户相关url
    url(r'user/', include('users.urls', namespace='user')),

    # 当debug=true
    url(r'^media/(?P<path>.*)', serve, {'document_root':MEDIA_ROOT}),

    # 当debug=false
    url(r'^static/(?P<path>.*)', serve, {'document_root': STATIC_ROOT}),
]

apps/courses/models.py
# -*-coding:utf-8-*-
from __future__ import unicode_literals
from datetime import datetime
from django.db import models

from organization.models import Org,Teacher


class Course(models.Model):
    course_org = models.ForeignKey(Org,verbose_name=u'所属大学',null=True)
    course_teacher = models.ForeignKey(Teacher,verbose_name=u'任课教师',null=True)
    name = models.CharField(max_length=50,verbose_name=u'课程名')
    desc = models.CharField(max_length=300,verbose_name=u'课程描述')
    detail = models.TextField(verbose_name=u'课程详情')
    degree = models.CharField(verbose_name=u'难度' ,choices=(('cj',u'初级'),('zj',u'中级'),('gj',u'高级')), max_length=10)
    category = models.CharField(max_length=30,verbose_name=u'课程类别',choices=(('bx',u'大学必修'),('xx',u'大学选修')),default='bx')
    learn_time = models.IntegerField(default=0,verbose_name=u'学习时长(h)')
    students = models.IntegerField(default=0,verbose_name=u'学习人数')
    fav_nums = models.IntegerField(default=0,verbose_name=u'收藏人数')
    tag = models.CharField(default='kx',choices=(('wx',u'文学'),('kx',u'科学'),('IT',u'IT')),max_length=10,verbose_name=u'标签')
    image = models.ImageField(upload_to='courses/%Y/%m',verbose_name=u'封面图',max_length=100)
    click_nums = models.IntegerField(default=0,verbose_name=u'点击数')
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')
    is_banner = models.BooleanField(default=False,verbose_name=u'是否首页轮播')

    class Meta:
        verbose_name = u'课程'
        verbose_name_plural = verbose_name
        ordering = ['-add_time']

    def __unicode__(self):
        return self.name

    def get_all_lessons(self):
        return self.lesson_set.all()

    # 得到机构课程总数
    def get_lesson_nums(self):
        return self.lesson_set.all().count()

    def get_all_sourses(self):
        return self.coursesource_set.all()


class Lesson(models.Model):
    course = models.ForeignKey(Course,verbose_name=u'课程')
    name = models.CharField(max_length=100,verbose_name=u'章节名')
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'章节'
        verbose_name_plural = verbose_name

    def get_all_videos(self):
        return self.video_set.all()


class Video(models.Model):
    lesson = models.ForeignKey(Lesson,verbose_name=u'章节')
    name = models.CharField(max_length=50,verbose_name=u'视频名')
    url = models.URLField(max_length=100, default='', verbose_name=u'课程链接')
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'视频'
        verbose_name_plural = verbose_name

class CourseSource(models.Model):
    course = models.ForeignKey(Course,verbose_name=u'课程')
    name = models.CharField(max_length=50, verbose_name=u'文件名')
    download = models.FileField(upload_to='resource/%Y/%m',verbose_name=u'资源文件')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name


class BannerCourse(Course):
    class Meta:
        verbose_name = u'首页轮播课程'
        verbose_name_plural = verbose_name
        proxy = True

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
  <meta charset="UTF-8">
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <title>{% block title %}机构列表 - 名校在线网{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/crumb.css' %}">
  {% block custom_css %}{% endblock %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>
</head>
<body>
<section class="headerwrap ">
  <header>
    <div class=" header">
      <div class="top">
        <div class="wp">
          <div class="fl"><p><b>欢迎来到名校在线网！</b></p></div>
          <!--登录后跳转-->
          {% if request.user.is_authenticated %}
            <div class="personal">
              <dl class="user fr">
                <dd>{{ request.user.nick_name }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                <dt><a href="{% url 'user:info_center' %}"><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></a></dt>
              </dl>
              <div class="userdetail">
                <dl>
                  <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}" /></dt>
                  <dd>
                    <h2>{{ request.user.nick_name }}</h2>
                    <p>{{ request.user.username }}</p>
                  </dd>
                </dl>
                <div class="btn">
                  <a class="personcenter fl" href="{% url 'user:info_center' %}">进入个人中心</a>
                  <a class="fr" href="{% url 'logout' %}">退出</a>
                </div>
              </div>
            </div>
            <a href="{% url 'user:my_message' %}">
              <div class="msg-num">
                <span id="MsgNum">{{ request.user.get_unread_message_nums }}</span>
              </div>
            </a>
          {% else %}
            <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
            <a style="color:white" class="fr loginbtn" href="{% url 'index' %}">登录</a>
          {% endif %}
        </div>
      </div>

      <div class="middle">
        <div class="wp">
{#          <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/djart.jpg' %}"/></a>#}
          <div class="searchbox fr">
            <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                课程
                            </span>
              <ul class="selectMenu" id="jsSelectMenu">
                <li data-value="course">课程</li>
                <li data-value="org">名校</li>
                <li data-value="teacher">名师</li>

              </ul>
            </div>
            <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
            <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
          </div>
        </div>
      </div>


      <nav>
        <div class="nav">
          <div class="wp">
            <ul>
              <li class="{% ifequal request.path '/' %}active{% endifequal %}"><a href="{% url 'index' %}">首页</a></li>
              <li class="{% ifequal request.path|slice:'9' '/org/list' %}active{% endifequal %}"><a href="{% url 'org:org_list' %}">名校</a></li>
              <li class="{% ifequal request.path|slice:'12' '/org/teacher' %}active{% endifequal %}"><a href="{% url 'org:teacher_list' %}">名师</a></li>
              <li class="{% ifequal request.path|slice:'7' '/course' %}active{% endifequal %}"><a href="{% url 'course:course_list' %}">课程</a> </li>
            </ul>
          </div>
        </div>
      </nav>

    </div>
  </header>
</section>
<!--crumbs start-->

<!--  面包屑 -->
{% block custom_bread %}
{% endblock %}

<!-- 页面 body 内容 -->
{% block custom_content %}
{% endblock %}

<!-- Footer -->
<footer>
		<div class="footer">
            <p class="copyright">©2017&nbsp;&centerdot;&nbsp;名校在线网&nbsp;&centerdot;&nbsp;南京&nbsp;<a style="color: white" href="http://www.miitbeian.gov.cn/publish/query/indexFirst.action">苏ICP备17049129号</a></p>
        </div>
</footer>


<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/unslider.js' %}"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js'  %}"></script>
<script src="{% static 'js/deco-common.js' %}"></script>

{% block custom_js %}{% endblock %}
</body>
</html>

templates/course-comment.html
{% extends 'list_base.html' %}
{% load staticfiles %}
{% block  title %}公开课评论页面 - 名校在线网{% endblock %}
{% block content %}
 <div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <style type="text/css">
                #course_name{
                    color: cadetblue;
                }
                #course_name:hover{
                    color: lightcyan;
                }
            </style>
            <div class="hd">
                <h2 class="l">&nbsp;&nbsp;<a id="course_name" href="{% url 'course:course_detail' this_course.id %}">{{ this_course.name }}</a></h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta">难度</span>
                    <span class="meta-value"><strong>{{ this_course.get_degree_display }}</strong></span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta">时长</span>
                    <span class="meta-value">{{ this_course.learn_time }}</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta">学习人数</span>
                    <span class="meta-value"><strong>{{ this_course.students }}</strong></span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
            <div class="content-wrap clearfix">
                <div class="content">
                    <div class="mod-tab-menu">
                        <ul class="course-menu clearfix">
                            <li><a class="ui-tabs-active " id="learnOn"  href="{% url 'course:course_video' this_course.id %}"><span>章节</span></a></li>
                            <li><a id="commentOn" class="active"><span>评论</span></a></li>
                        </ul>
                    </div>

                    <!--发布评论-->
                    <div id="js-pub-container" class="issques clearfix js-form">
                        <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                            <textarea id="comment_text"></textarea>
                        </div>
                        <input type="button" id="comment_btn" class="pub-btn" data-cid="452" value="发表评论">
                        <p class="global-errortip js-global-error"></p>
                    </div>
                    <div id="course_note">
                        <ul class="mod-post" id="comment-list">
                            {% for cm in all_comment %}
                            <li class="post-row">
                                <div class="media">
                                    <span target="_blank"><img src='{{ MEDIA_URL }}{{ cm.user.image }}' width='40' height='40' /></span>
                                </div>
                                <div class="bd">
                                    <div class="tit">
                                        <span target="_blank">{{ cm.user.nick_name }} 说：</span>
                                    </div>
                                    <p class="cnt">{{ cm.comment }}</p>
                                    <div class="footer clearfix">
                                        <span title="创建时间" class="l timeago">{{ cm.add_time }}</span>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="aside r">
                    <div class="bd">

                        <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">

                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;前端页面</span>
                                <a href="../media/course/resource/2016/11/media.zip" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>

                        </ul>
                    </div>
                        <div class="box mb40">
                                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="{% url 'org:teacher_detail' course_teacher.id %}" target="_blank">
                            <img src='{{ MEDIA_URL }}{{ course_teacher.photo }}' width='80' height='80' />
                            </a>
                    <span class="tit">
                        <a href="{% url 'org:teacher_detail' course_teacher.id %}" target="_blank">{{ course_teacher }}</a>
                    </span>
                    <span class="job">{{ course_teacher.work_position }}</span>
                    </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">零基础即可参加课程</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ this_course.name }}</dd>
                            </dl>
                        </div>
                    </div>
                    <div class="cp-other-learned  js-comp-tabs">
                            <div class="cp-header clearfix">
                                <h2 class="cp-tit l">该课的同学还学过</h2>
                            </div>
                            <div class="cp-body">
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                    <!-- img 200 x 112 -->
                                    <ul class="other-list">

                                        <li class="curr">
                                            <a href="{% url 'course:course_detail' recommend_course.id %}" target="_blank">
                                                <img src="{{ MEDIA_URL }}{{ recommend_course.course.image }}" alt="{{ recommend_course.course.name }}">
                                                <span class="name autowrap">{{ recommend_course.course.name }}</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </div>

        </div>
    </div>
</div>
<script type="text/javascript">
      // comment_text,comment_btn
    $(document).ready(function(){
        $.ajaxSetup({
        data: {csrfmiddlewaretoken: '{{ csrf_token }}' }
                });
      $("#comment_btn").click(function(){
        var text= $("#comment_text").val();
        if(text == ""){
            alert("评论不能为空");
            return
        }
        $.post("{% url 'course:add_comment' %}",{'text':text,'course_id':{{this_course.id}} }, function(ret){
            window.location.reload();
        })
      });
    });
</script>

{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/course-comment.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
{% endblock %}

templates/usercenter-fav-course.html
{% extends 'usercenter-info.html' %}
{% load staticfiles %}
{% block title %}我的收藏 - 名校在线网{% endblock %}

{% block page_path %}
    <a>我的收藏</a>
{% endblock %}

{% block left_content %}
	<div class="left">
        <ul>
            <li ><a href="{% url 'user:info_center' %}">个人资料</a></li>
            <li ><a href="{% url 'user:my_course' %}">我的课程</a></li>
            <li class="active2">我的收藏</li>
            <li >
                <a href="{% url 'user:my_message' %}" style="position: relative;">
                    我的消息
                </a>
            </li>
        </ul>
	</div>
{% endblock %}

{% block right_content %}
<div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'user:my_fav_org' %}">名校</a> </li>
                        <li><a href="{% url 'user:my_fav_teacher' %}">名师 </a></li>
                        <li class="active">课程</li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in fav_courses %}
                        <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href=""{% url 'course:course_detail' course.id %}""><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_time }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                        {% endfor %}



                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/usercenter-fav-org.html
{% extends 'usercenter-info.html' %}
{% load staticfiles %}
{% block title %}我的收藏 - 名校在线网{% endblock %}

{% block page_path %}
    <a>我的收藏</a>
{% endblock %}

{% block left_content %}
	<div class="left">
        <ul>
            <li ><a href="{% url 'user:info_center' %}">个人资料</a></li>
            <li ><a href="{% url 'user:my_course' %}">我的课程</a></li>
            <li class="active2">我的收藏</li>
            <li >
                <a href="{% url 'user:my_message' %}" style="position: relative;">
                    我的消息
                </a>
            </li>
        </ul>
	</div>
{% endblock %}

{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active">名校</li>
                        <li><a href="{% url 'user:my_fav_teacher' %}">名师 </a></li>
                        <li><a href="{% url 'user:my_fav_course' %}">课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">

                    {% for org in fav_orgs %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:org_home' org.id %}">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'org:org_home' org.id %}">{{ org.name }}</a></h1>

                                <span class="c8 clear">{{ org.city}}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>


	</div>
{% endblock %}

templates/usercenter-message.html
{% extends 'usercenter-info.html' %}
{% block title %}我的消息 - 名校在线网{% endblock %}
{% block page_path %}
    <a>我的消息</a>
{% endblock %}

{% block left_content %}
	<div class="left">
        <ul>
            <li ><a href="{% url 'user:info_center' %}">个人资料</a></li>
            <li ><a href="{% url 'user:my_course' %}">我的课程</a></li>
            <li ><a href="{% url 'user:my_fav_org' %}">我的收藏</a></li>
            <li class="active2">
                <a href="#" style="position: relative;" >
                    我的消息
                </a>
            </li>
        </ul>
	</div>
{% endblock %}

{% block right_content %}
<div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的消息</h1>
			</div>

		</div>
		<div class="personal_des permessage">
			<div class="head">
				<ul class="tab_header messagehead">
					<li class="active">个人消息</li>
				</ul>
			</div>

        {% for message in messages.object_list %}
			<div class="messagelist">

                    <div class="messages">
                        <div class="fr">
                            <div class="top"><span class="fl time">{{ message.add_time|date:"Y-m-d H:i:s" }}</span><span class="fr btn foldbtn"></span></div>
                            <p>
                                {{ message.message }}
                            </p>
                        </div>
                    </div>



			</div>
        {% endfor %}

			<div class="pageturn pagerright">
                <ul class="pagelist">
                        {# -----------页码---------#}
                            {% if messages.has_previous %}
                    <li class="long"><a href="?{{ messages.previous_page_number.querystring }}">前一页</a></li>
                {% endif %}
                {% for page in messages.pages %}
                    {% if page %}
                        {% ifequal page messages.number %}
                            <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                        {% else %}
                            <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                        {% endifequal %}
                    {% endif %}
                {% endfor %}
                {% if messages.has_next %}
                    <li class="long"><a href="?{{ messages.next_page_number.querystring }}">下一页</a></li>
                {% endif %}

                        </ul>
            </div>
		</div>

	</div>
{% endblock %}

templates/usercenter-mycourse.html
{% extends 'usercenter-info.html' %}
{% block title %}我的课程 - 名校在线网{% endblock %}
{% block page_path %}
    <a>我的课程</a>
{% endblock %}

{% block left_content %}
	<div class="left">
        <ul>
            <li ><a href="{% url 'user:info_center' %}">个人资料</a></li>
            <li class="active2">我的课程</li>
            <li ><a href="{% url 'user:my_fav_org' %}">我的收藏</a></li>
            <li >
                <a href="{% url 'user:my_message' %}" style="position: relative;">
                    我的消息
                </a>
            </li>
        </ul>
	</div>
{% endblock %}

{% block right_content %}
    <div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的课程</h1>
			</div>
		</div>
		<div class="personal_des permessage">
			<div class="companycenter">
				<div class="group_list brief">
                    {% for course in user_courses %}
                    <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' course.id %}">
                                <img width="214" height="190" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' course.id %}"><h2>{{ course.name}}</h2></a>
                                <span class="fl">课时：<i class="key">{{ course.learn_time }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org }}</span>
                                <span class="star fr  notlogin" data-favid="15">{{ course.fav_nums }}</span>
                            </div>
                        </div>
                    {% endfor %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}